name: update README.md code blocks
on: [push, pull_request]
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Markdown autodocs
        uses: dineshsonachalam/markdown-autodocs@v1.0.4
        with:
          # Optional, defaults to author of the commit that triggered the run
          commit_author: Author <actions@github.com>
          # Optional, defaults to "actions@github.com"
          commit_user_email: actions@github.com
          # Optional, but recommended
          # Defaults to "Apply automatic changes"
          commit_message: Apply automatic changes
          # Optional branch name where commit should be pushed to.
          # Defaults to the current branch.
          #    branch: feature-123
          # Optional output file paths, defaults to '[./README.md]'.
          output_file_paths: '[./docs/getting-started.md,./docs/advanced-microservice.md,./docs/advanced-zeebe.md,./docs/advanced-timers.md,./docs/implementation-task-handlers.md,./docs/advanced-multiple-versions.md]'
          # Categories to automatically sync or transform its contents in the markdown files.
          # Defaults to '[code-block,json-to-html-table,workflow-artifact-table]'
          categories: '[code-block]'

